### ISSUE TITLE
.hire command is a bork

### ISSUE THREAD

**Issue by YeahItsRock** [Gabolicious/AlfredBot#19]
There was an error. Gabo says There was an error updating the applicants status.

Happened when Vampy tried to manually rehire someone

**Comment by gabotaco** [comment]
Fixed in https://github.com/rhit-corridg/AlfredBot/commit/20758c026ac8884f8d033c03b50aaa43d8ed715d

**Comment by YeahItsRock** [comment]
Has this been merged? This is still an issue. If it hasn't been merged, maybe we should test and verify fixes before closing tickets?

**Comment by YeahItsRock** [comment]
"There was an error. Gabo says There was an error creating the member row." 

New error on .hire command

**Comment by gabotaco** [comment]
I'm going to assume this is fixed now
