### ISSUE TITLE
Adding Some Information Commands

### ISSUE THREAD

**Issue by TechZack** [Gabolicious/AlfredBot#20]
With regards to adding some company information commands especially between handbooks or guides.  These would only be accessible to Internal Users.

/handbook would reply with the Handbook link and depending on the role/discord it will send them the right Handbook for the company that they are in. 

If anyone has any other ideas of some more informational commands please shout them out!

**Comment by YeahItsRock** [comment]
This already exists, type .handbook or /handbook

**Comment by TechZack** [comment]
I'm blind haha. Close this then.
