### ISSUE TITLE
Add more details to the deadline command output?

### ISSUE THREAD

**Issue by Joeyd718** [Gabolicious/AlfredBot#22]
Could we add more details to the deadline command? such as it specifying who the deadline is for, that way you can tell easily if you fuck up trying to check some ones deadline and it just gives you your own :heh:
![Discord_xv1iFIHCF7](https://user-images.githubusercontent.com/105568856/168450795-f14427f8-d5a9-4f74-9d1e-3681c4459980.png)

**Comment by YeahItsRock** [comment]
Why not just use .vouchers and /vouchers-m?

Also, add what details you'd want to see and what format you'd want to see it in.

**Comment by Joeyd718** [comment]
Yeah i supposed just using vouchers is a good alternate.

Really I'm just saying to add the persons name to it so you don't mistake your deadline for theirs's. You can see it kind happen to Extenze here https://discord.com/channels/487285826544205845/944976053821120572/975072536758992976

With 0 context its easy to mistake that as being theirs's, when its yours :P

Whether that would be pinging the person, putting their discord name or IGN in plain text, or something along those lines. Up to y'all to decide what would be best.

So for the format it could stay as it is currently, just add their name to the start of it "blah blahs Deadline: time time time"

**Comment by gabotaco** [comment]
Fixed in https://github.com/rhit-corridg/AlfredBot/commit/264b01c7ea426d455fbf6abb558da6fee812c941
