### ISSUE TITLE
.top10 command in RTS Discord causes Alfred to crash; attached log in comments

### ISSUE THREAD

**Issue by YeahItsRock** [Gabolicious/AlfredBot#23]
![image](https://user-images.githubusercontent.com/105456028/168486920-a9623fcd-a0cf-42c1-a6bd-eb28bcb0724a.png)

**Comment by gabotaco** [comment]
https://github.com/rhit-corridg/AlfredBot/commit/56b7722973164675611bd4cc5ede5134380d3111
