### ISSUE TITLE
Add reaction messages to PIGS server

### ISSUE THREAD

**Issue by YeahItsRock** [Gabolicious/AlfredBot#25]
- Refresh Roles: 
- Same effect as this message: https://discord.com/channels/447157938390433792/705179062347366513/705179916915834891

Also add reaction to add these roles:

Warthogs
572838338470346757
Edgy
498885132468486175

PIGS Channel ID
976981250516594718

**Comment by gabotaco** [comment]
This exists already

https://discord.com/channels/487285826544205845/705249536477495337/705249747950108752

You just never made it public
